import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Import your Lab modules
from utils.data_loader import load_and_prep_data
from library.features import (
    add_log_returns, add_atr, add_normalized_slope, 
    add_price_zscore, add_shannon_entropy, add_hurst_exponent, add_markov_regime,add_volatility_ratio
)

def run_visualization():
    print("Loading data and calculating quant features...")
    # Load a smaller slice of data so the chart is readable
    df = load_and_prep_data("data/gbpusd_data.csv", "2020-01-01", "2026-02-27", "4h")
    
    # --- ADD THIS SAFETY GUARD ---
    if df is None or df.empty:
        print("❌ ERROR: No data was loaded!")
        print("Please check that 'gbpusd_data.csv' has data for the requested dates.")
        return  # Stop the script here instead of crashing

    df = add_log_returns(df)
    df = add_atr(df, lookback=14)

    # Apply Quant Features
    df = add_log_returns(df)
    df = add_atr(df, lookback=14)
    df = add_volatility_ratio(df, short_lookback=14, long_lookback=100)
    df = add_normalized_slope(df, lookback=20, atr_lookback=14)
    df = add_price_zscore(df, lookback=50)
    df = add_shannon_entropy(df, lookback=50)
    df = add_hurst_exponent(df, lookback=100)
    df = add_markov_regime(df)
    
    # Drop NaNs generated by the rolling windows
    df.dropna(inplace=True)

    print("Generating Chart...")
    # Create a 4-pane stacked chart
    fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(15, 12), sharex=True)
    plt.subplots_adjust(hspace=0.1)

    # --- PANE 1: Price Action & Markov Regimes ---
    axes[0].plot(df.index, df['Close'], color='black', linewidth=1)
    axes[0].set_title('GBP/USD (1H) - Background Colors represent Markov Regimes', loc='left')
    axes[0].set_ylabel('Price')
    
    # Color background based on Markov Regime
    regime_colors = {
        'High Vol / Bearish': 'lightcoral',
        'High Vol / Bullish': 'lightgreen',
        'Low Vol / Bearish': 'lightgray',
        'Low Vol / Bullish': 'lightblue'
    }
    
    # Shade the background
    for i in range(1, len(df)):
        current_regime = df['Markov_Regime'].iloc[i]
        if current_regime in regime_colors:
            axes[0].axvspan(df.index[i-1], df.index[i], color=regime_colors[current_regime], alpha=0.3, lw=0)

    # --- PANE 2: Price Z-Score ---
    axes[1].plot(df.index, df['Price_ZScore'], color='blue', linewidth=1)
    axes[1].axhline(2, color='red', linestyle='--', alpha=0.5)   # Overbought threshold
    axes[1].axhline(-2, color='green', linestyle='--', alpha=0.5) # Oversold threshold
    axes[1].axhline(0, color='gray', linestyle='-', alpha=0.3)
    axes[1].set_ylabel('Price Z-Score')
    axes[1].legend(['Z-Score', '+2 (Overextended)', '-2 (Overextended)'], loc='upper left')

    # --- PANE 3: Hurst Exponent ---
    axes[2].plot(df.index, df['Hurst'], color='purple', linewidth=1)
    axes[2].axhline(0.5, color='black', linestyle='--', alpha=0.5) # Random Walk line
    axes[2].set_ylabel('Hurst Exponent')
    axes[2].legend(['Hurst', '0.5 = Random Walk'], loc='upper left')

    # --- PANE 4: Shannon Entropy ---
    axes[3].plot(df.index, df['Entropy'], color='orange', linewidth=1)
    axes[3].set_ylabel('Entropy (Chaos)')
    axes[3].set_title('High Entropy = Pure Noise / Low Entropy = Organized Structure', loc='left', fontsize=10)

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    run_visualization()