import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Import your Lab modules
from utils.data_loader import load_and_prep_data
from library.features import (
    add_log_returns, add_atr, add_normalized_slope, 
    add_price_zscore, add_shannon_entropy, add_hurst_exponent, add_markov_regime,add_volatility_ratio, add_hmm_volatility_regime
)

def run_visualization():
    print("Loading data and calculating quant features...")
    # Load a smaller slice of data so the chart is readable
    df = load_and_prep_data("data/gbpusd_data.csv", "2020-01-01", "2026-02-27", "4h")
    
    # --- ADD THIS SAFETY GUARD ---
    if df is None or df.empty:
        print("❌ ERROR: No data was loaded!")
        print("Please check that 'gbpusd_data.csv' has data for the requested dates.")
        return  # Stop the script here instead of crashing

    df = add_log_returns(df)
    df = add_atr(df, lookback=14)

    # Apply Quant Features
    df = add_log_returns(df)
    df = add_atr(df, lookback=14)
    df = add_volatility_ratio(df, short_lookback=14, long_lookback=100)
    df = add_normalized_slope(df, lookback=20, atr_lookback=14)
    df = add_price_zscore(df, lookback=50)
    df = add_shannon_entropy(df, lookback=50)
    df = add_hurst_exponent(df, lookback=100)
    df = add_hmm_volatility_regime(df)
    
    # Drop NaNs generated by the rolling windows
    df.dropna(inplace=True)

    print("Generating Chart...")
    # Create a 4-pane stacked chart
    # Create a 4-pane stacked chart
    fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(15, 12), sharex=True)
    plt.subplots_adjust(hspace=0.3)

    # --- PANE 1: Price Action (Cleaned, no more old background colors) ---
    axes[0].plot(df.index, df['Close'], color='black', linewidth=1)
    axes[0].set_title('GBP/USD (1H)', loc='left')
    axes[0].set_ylabel('Price')
    axes[0].grid(True, linestyle='--', alpha=0.5)

    # --- PANE 2: HMM Probability of High Volatility (Like your screenshot) ---
    axes[1].plot(df.index, df['High_Vol_Prob'], color='firebrick', linewidth=1.5)
    axes[1].fill_between(df.index, df['High_Vol_Prob'], 0, color='firebrick', alpha=0.3)
    axes[1].set_title('Модель Маркова: Вероятность нахождения в Режиме Высокой Волатильности', loc='center')
    axes[1].set_ylabel('Вероятность (0 - 1)')
    axes[1].set_ylim(-0.05, 1.05)
    axes[1].grid(True, linestyle='--', alpha=0.6)

    # --- PANE 3: Price Z-Score ---
    axes[2].plot(df.index, df['Price_ZScore'], color='blue', linewidth=1)
    axes[2].axhline(2, color='red', linestyle='--', alpha=0.5)   
    axes[2].axhline(-2, color='green', linestyle='--', alpha=0.5) 
    axes[2].axhline(0, color='gray', linestyle='-', alpha=0.3)
    axes[2].set_ylabel('Price Z-Score')
    axes[2].legend(['Z-Score', '+2 (Overextended)', '-2 (Overextended)'], loc='upper left')

    # --- PANE 4: Hurst Exponent ---
    axes[3].plot(df.index, df['Hurst'], color='purple', linewidth=1)
    axes[3].axhline(0.5, color='black', linestyle='--', alpha=0.5) 
    axes[3].set_ylabel('Hurst Exponent')
    axes[3].legend(['Hurst', '0.5 = Random Walk'], loc='upper left')

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    run_visualization()